name: Build custom Presidio Docker Image

on:
  workflow_dispatch:

jobs:
  setup-presidio:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Clone Presidio repository
      run: |
        git clone https://github.com/microsoft/presidio.git
        echo "Presidio repository cloned successfully"
        
    - name: Copy YAML files from custom folder to presidio-analyzer
      run: |
        echo "Copying YAML files from custom folder to presidio-analyzer..."
        find custom -name "*.yaml" -exec cp {} presidio-analyzer/presidio-analyzer/conf \;
        echo "YAML config files copied successfully"
        
    - name: Build Docker image
      run: |
        docker build ./presidio/presidio-anonymizer -t sheyenrath/presidio-anonymizer:latest
        echo "Docker image built successfully"
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: sheyenrath
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push Docker image to Docker Hub
      run: |
        docker push sheyenrath/presidio-anonymizer:latest
        echo "Docker image pushed to Docker Hub successfully"
